### ISSUE TITLE
byte не для счёта, а для работы на уровне байт с данными

### ISSUE THREAD

**Issue by coursar** [ArkhipovMarat/Distance-calculator#3]
https://github.com/ArkhipovMarat/ArkhipovM_1_1/blob/f5082641bcfed8bbcb018b5c7a17de4aad4b839f/src/Main.java#L15

**Comment by ArkhipovMarat** [comment]
поменять на short или int?
подумал, что для хранения значения о запасе топлива достаточно byte или 
такая экономия не нужна?

**Comment by coursar** [comment]
Договаривались, что при счёте:
- double для вещественных
- int для целых (long, если большие)

**Comment by ArkhipovMarat** [comment]
Ясно. Исправил
