### ISSUE TITLE
Почему не double?

### ISSUE THREAD

**Issue by coursar** [ArkhipovMarat/Distance-calculator#4]
https://github.com/ArkhipovMarat/ArkhipovM_1_1/blob/f5082641bcfed8bbcb018b5c7a17de4aad4b839f/src/Main.java#L17

**Comment by ArkhipovMarat** [comment]
посчитал что для хранения значения дистанции достаточно будет float,
соответственно зачем вводить double?

**Comment by ArkhipovMarat** [comment]
Исправил
