### ISSUE TITLE
Зачем приводить к double если итак выражение типа double?

### ISSUE THREAD

**Issue by coursar** [ArkhipovMarat/Distance-calculator#6]
https://github.com/ArkhipovMarat/Distance-calculator/blob/aab6c2d1855bd1089b2dc2efcdbd36039239eb96/src/Main.java#L10

**Comment by coursar** [comment]
Не исправлено

**Comment by ArkhipovMarat** [comment]
исправлено

**Comment by coursar** [comment]
Issue нужно закрывать сообщениями коммита, а не вручную
